#!/usr/bin/env bash

cd /autograder/source
git clean -f
git pull

# Makes TeX Log script executable
export LC_ALL=C
chmod +x /autograder/source/texloganalyser

# Runs autograder
cd /autograder/submission
cp /autograder/source/compile_and_grade.py /autograder/submission/compile_and_grade.py
python3 compile_and_grade.py