#!/usr/bin/env bash

cd /autograder/source
git clean -f
git pull

# Makes TeX Log script executable
export LC_ALL=C
chmod +x /autograder/source/texloganalyser

# Runs autograder
cd ../submission
python3 ../source/compile_and_grade.py